name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build and start application
      run: |
        ./gradlew build -x test
        nohup ./gradlew bootRun > app.log 2>&1 &
        # Wait for the application to start
        sleep 30
        
    - name: Install Bruno
      run: |
        npm install -g @usebruno/cli
        
    - name: Run Bruno API tests
      run: |
        # Run Bruno tests
        bru run --env local ./bruno/collections/book-api
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: api-test-results
        path: |
          app.log
          bruno-report/
        retention-days: 7
        
    - name: Stop application
      if: always()
      run: |
        # Find and kill the Java process running the application
        pkill -f 'java.*bootRun' || true
